<?php

namespace Manager\Bundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function getCompanies($step, $searchText = "")
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("
                    SELECT p FROM ManagerBundle:Company p WHERE p.step = :step and p.rejected = 0 and p.name LIKE '%$searchText%' and p.trashed = 0
        ");
        $query->setParameter('step', $step);
        return $query;
    }

    public function getAllCompaniesQuery($searchText = "")
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(" SELECT p FROM ManagerBundle:Company p WHERE p.name LIKE '%$searchText%'");
        return $query;
    }

    public function getRejectedListQuery($searchText = "")
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(" SELECT p FROM ManagerBundle:Company p WHERE p.rejected = 1 and p.name LIKE '%$searchText%' and p.trashed = 0");
        return $query;
    }

    public function getReportedCompamnies($searchText = "")
    {
        $em = $this->getEntityManager();
    }
}
