<?php

namespace Manager\Bundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Manager\Bundle\Entity\Company;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDocumentsQuery(Company $company)
    {
        $em = $this->getEntityManager();
        $repository = $em->getRepository("ManagerBundle:Document");
        $queryBuilder = $repository->createQueryBuilder('p');

        $queryBuilder->where("p.company = :company")
            ->setParameter("company",$company);

        return $queryBuilder->getQuery();
    }
}
