<?php

namespace Manager\Bundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepRepository extends EntityRepository
{
    public function getStepByName($name)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT p FROM ManagerBundle:Step p WHERE p.name LIKE %'.$name.'%
        ');

        return $query->getOneOrNullResult();
    }
}
