parameters:
#    manager..example.class: Manager\Bundle\Example

services:
    public.functions:
        class:     Manager\Bundle\Extensions\Extension
        tags:
            - { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"

    mybundle.tblprefix_subscriber:
            class: Manager\Bundle\Subscriber\TablePrefixSubscriber
            arguments: [%database_prefix%]
            tags:
                - { name: doctrine.event_subscriber }