parameters:
#    manager..example.class: Manager\Bundle\Example

services:
    public.functions:
        class:     Manager\Bundle\Extensions\Extension
        tags:
            - { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"
    public.forms:
        class:  Manager\Bundle\Extensions\FormExtension
        tags:
            - { name: twig.extension }
        arguments:
            forms: "@form.factory"
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }